import type { DashboardDataset } from "@/lib/types";

export const demoDataset: DashboardDataset = {
  workbookName: "Demo Dataset",
  loadedAt: new Date().toISOString(),
  sheets: [],
  hiddenDependencySheets: [],
  products: [
    {
      rowId: "Primary-1",
      category: "Primary",
      name: "Nifty Accelerator - Alpha",
      issuer: "ARGFL",
      isin: "INE000000001",
      underlying: "Nifty",
      series: "Series I",
      tradeAmount: 32000000,
      couponPercent: 0.18,
      tenorDays: 730,
      tenorBucket: "2 Year",
      maturityRaw: "31-Dec-2027",
      lastObservationDateRaw: "30-Nov-2027",
      formulaText: "IF(Z>=0,MIN(32%,12%+(Z*150%)),MAX(-100%,Z*1.2))",
      productExplanation: "Accelerated upside participation with guarded downside.",
      principalProtection: "Non-Principal Protected",
      listing: "Listed",
      productType: "Equity",
      raw: {},
    },
    {
      rowId: "Primary-2",
      category: "Primary",
      name: "Yield Enhancer - Vega",
      issuer: "CITI",
      isin: "INE000000002",
      underlying: "Nifty",
      series: "Series IV",
      tradeAmount: 18000000,
      couponPercent: 0.14,
      tenorDays: 540,
      tenorBucket: "18 Month",
      maturityRaw: "30-Jun-2027",
      lastObservationDateRaw: "31-May-2027",
      formulaText: "MAX(0,12%+Z)",
      productExplanation: "Fixed carry plus measured index participation.",
      principalProtection: "Principal Protected",
      listing: "Listed",
      productType: "Debt",
      raw: {},
    },
  ],
  categorySummaries: [
    {
      category: "Primary",
      productCount: 2,
      liveNotional: 50000000,
      averageCoupon: 0.16,
      listedShare: 1,
      principalProtectedShare: 0.5,
      topIssuers: [
        { name: "ARGFL", value: 32000000 },
        { name: "CITI", value: 18000000 },
      ],
      tenorMix: [
        { bucket: "2 Year", value: 32000000 },
        { bucket: "18 Month", value: 18000000 },
      ],
      payoffProfiles: [
        {
          name: "Nifty Accelerator - Alpha",
          formula: "IF(Z>=0,MIN(32%,12%+(Z*150%)),MAX(-100%,Z*1.2))",
        },
      ],
    },
  ],
  validationIssues: [
    {
      severity: "info",
      category: "Demo",
      message: "Upload the latest master workbook to replace this demo snapshot with live calculations.",
    },
  ],
  formulaCatalog: [],
};
